apiVersion: v1
kind: Service
metadata:
  name: enterprise-system-20260623-200212-0f7pdz89v7kd-service
spec:
  selector:
    app: enterprise-system-20260623-200212-0f7pdz89v7kd
  ports:
  - port: 80
    targetPort: 8000
  type: ClusterIP
